// src/lib/iconTypes.ts
export type IconType = {
  name: string;
  path: string;
  searchTerms: string[];
  categories: string[];
};

// Utility function to get the correct path
const getIconPath = (iconName: string) => {
  // For GitHub Pages, we need to include the repo name in production
  const basePath = "";
  return `${basePath}/icons/${iconName}`;
};

// Category Names
export const categoryNames = [
  "Accessibility",
  "Animals",
  "Accounts & Access",
  "Arrows",
  "Audio & Video",
  "Automotive",
  "Buildings",
  "Business & Finance",
  "Charity & Volunteer",
  "Clothing & Accessories",
  "Communication",
  "Content",
  "Design & Development",
  "E-commerce",
  "Education",
  "Emoji",
  "Energy & Environment",
  "File Type",
  "Fitness & Health",
  "Food & Drink",
  "Gaming",
  "Holidays",
  "Home & Garden",
  "Logistics",
  "Maps & Navigation",
  "Media & News",
  "Medical",
  "Military & Security",
  "Music",
  "Nature",
  "Objects & Tools",
  "Payment & Shopping",
  "Photography",
  "Science & Education",
  "Social & Messaging",
  "Space",
  "Sports & Activities",
  "Technology",
  "Transportation",
  "Travel & Places",
  "Weather",
  "Writing & Editing",
];

export const iconTypes: IconType[] = [
  /* Accessibility */
  {
    name: "Accessibility",
    path: getIconPath("accessibility.svg"),
    searchTerms: [
      "accessibility",
      "wheelchair",
      "disability",
      "handicap",
      "ramp",
      "stairs",
    ],
    categories: ["Accessibility"],
  },
  {
    name: "Baby",
    path: getIconPath("baby.svg"),
    searchTerms: ["baby", "child", "infant", "toddler", "newborn", "crib"],
    categories: ["Accessibility"],
  },
  {
    name: "Ear",
    path: getIconPath("ear.svg"),
    searchTerms: ["ear", "hearing", "listen", "sound", "deaf", "earlobe"],
    categories: ["Accessibility"],
  },
  {
    name: "Ear Off",
    path: getIconPath("ear-off.svg"),
    searchTerms: ["ear off", "deaf", "hearing", "loss", "mute", "sound"],
    categories: ["Accessibility"],
  },
  {
    name: "Eye",
    path: getIconPath("eye.svg"),
    searchTerms: ["eye", "vision", "look", "see", "sight", "watch"],
    categories: ["Accessibility"],
  },
  {
    name: "Eye Closed",
    path: getIconPath("eye-closed.svg"),
    searchTerms: ["eye closed", "sleep", "rest", "nap", "blink", "shut"],
    categories: ["Accessibility"],
  },
  {
    name: "Eye Off",
    path: getIconPath("eye-off.svg"),
    searchTerms: [
      "eye off",
      "blind",
      "sightless",
      "vision",
      "loss",
      "invisible",
    ],
    categories: ["Accessibility"],
  },
  {
    name: "Glasses",
    path: getIconPath("glasses.svg"),
    searchTerms: [
      "glasses",
      "spectacles",
      "eyewear",
      "vision",
      "sight",
      "frames",
    ],
    categories: ["Accessibility"],
  },
  {
    name: "Hand",
    path: getIconPath("hand.svg"),
    searchTerms: ["hand", "palm", "fingers", "gesture", "wave", "point"],
    categories: ["Accessibility"],
  },
  {
    name: "Person Standing",
    path: getIconPath("person-standing.svg"),
    searchTerms: [
      "person standing",
      "human",
      "figure",
      "stand",
      "pose",
      "mannequin",
    ],
    categories: ["Accessibility"],
  },
  {
    name: "Scan Eye",
    path: getIconPath("scan-eye.svg"),
    searchTerms: [
      "scan eye",
      "retina",
      "iris",
      "biometric",
      "security",
      "scan",
    ],
    categories: ["Accessibility"],
  },
  {
    name: "Speech",
    path: getIconPath("speech.svg"),
    searchTerms: ["speech", "talk", "say", "voice", "communicate", "words"],
    categories: ["Accessibility"],
  },
  /* Animals */
  {
    name: "Bear Face",
    path: getIconPath("bear-face.svg"),
    searchTerms: ["bear face", "animal", "wild", "grizzly", "furry", "brown"],
    categories: ["Animals"],
  },
  {
    name: "Bee",
    path: getIconPath("bee.svg"),
    searchTerms: ["bee", "insect", "wings", "stinger", "honey", "hive"],
    categories: ["Animals"],
  },
  {
    name: "Beetle Scarab",
    path: getIconPath("beetle-scarab.svg"),
    searchTerms: [
      "beetle scarab",
      "insect",
      "wings",
      "beetle",
      "bug",
      "scarab",
    ],
    categories: ["Animals"],
  },
  {
    name: "Bird",
    path: getIconPath("bird.svg"),
    searchTerms: ["bird", "animal", "flying", "wings", "feathers", "beak"],
    categories: ["Animals"],
  },
  {
    name: "Bull Head",
    path: getIconPath("bull-head.svg"),
    searchTerms: ["bull head", "animal", "cow", "horn", "strong", "power"],
    categories: ["Animals"],
  },
  {
    name: "Bug",
    path: getIconPath("bug.svg"),
    searchTerms: ["bug", "insect", "antennae", "legs", " wings"],
    categories: ["Animals"],
  },
  {
    name: "Butterfly",
    path: getIconPath("butterfly.svg"),
    searchTerms: ["butterfly", "insect", "wings", "flutter", "colorful", "fly"],
    categories: ["Animals"],
  },
  {
    name: "Cat",
    path: getIconPath("cat.svg"),
    searchTerms: ["cat", "animal", "feline", "whiskers", "ears", "paws"],
    categories: ["Animals"],
  },
  {
    name: "Cat Big",
    path: getIconPath("cat-big.svg"),
    searchTerms: ["cat big", "animal", "feline", "whiskers", "ears", "paws"],
    categories: ["Animals"],
  },
  {
    name: "Chameleon",
    path: getIconPath("chameleon.svg"),
    searchTerms: ["chameleon", "lizard", "reptile", "camouflage", "colorful"],
    categories: ["Animals"],
  },
  {
    name: "Cow Head",
    path: getIconPath("cow-head.svg"),
    searchTerms: ["cow head", "animal", "moo", "horn", "strong", "power"],
    categories: ["Animals"],
  },
  {
    name: "Crab",
    path: getIconPath("crab.svg"),
    searchTerms: ["crab", "animal", "sea", "claws", "shell", "legs"],
    categories: ["Animals"],
  },
  {
    name: "Dog",
    path: getIconPath("dog.svg"),
    searchTerms: ["dog", "animal", "canine", "paws", "ears", "tail"],
    categories: ["Animals"],
  },
  {
    name: "Elephant Face",
    path: getIconPath("elephant-face.svg"),
    searchTerms: ["elephant face", "animal", "trunk", "tusks", "ears", "gray"],
    categories: ["Animals"],
  },
  {
    name: "Elephant",
    path: getIconPath("elephant.svg"),
    searchTerms: ["elephant", "animal", "trunk", "tusks", "ears", "gray"],
    categories: ["Animals"],
  },
  {
    name: "Fish",
    path: getIconPath("fish.svg"),
    searchTerms: ["fish", "animal", "swimming", "fins", "gills", "scales"],
    categories: ["Animals"],
  },
  {
    name: "Fox Face Tail",
    path: getIconPath("fox-face-tail.svg"),
    searchTerms: ["fox face tail", "animal", "red", "ears", "whiskers", "tail"],
    categories: ["Animals"],
  },
  {
    name: "Frog Face",
    path: getIconPath("frog-face.svg"),
    searchTerms: ["frog face", "animal", "amphibian", "green", "eyes", "mouth"],
    categories: ["Animals"],
  },
  {
    name: "Hedgehog",
    path: getIconPath("hedgehog.svg"),
    searchTerms: ["hedgehog", "animal", "spikes", "prickly", "quills", "spiny"],
    categories: ["Animals"],
  },
  {
    name: "Horse Head",
    path: getIconPath("horse-head.svg"),
    searchTerms: ["horse head", "animal", "mane", "ears", "whinny", "neigh"],
    categories: ["Animals"],
  },
  {
    name: "Owl",
    path: getIconPath("owl.svg"),
    searchTerms: ["owl", "animal", "bird", "wings", "feathers", "eyes"],
    categories: ["Animals"],
  },
  {
    name: "Paw Print",
    path: getIconPath("paw-print.svg"),
    searchTerms: ["paw print", "animal", "footprint", "dog", "cat"],
    categories: ["Animals"],
  },
  {
    name: "Penguin",
    path: getIconPath("penguin.svg"),
    searchTerms: ["penguin", "animal", "bird", "wings", "feathers", "swim"],
    categories: ["Animals"],
  },
  {
    name: "Pig",
    path: getIconPath("pig.svg"),
    searchTerms: ["pig", "animal", "snout", "ears", "tail", "oink"],
    categories: ["Animals"],
  },
  {
    name: "Pig Head",
    path: getIconPath("pig-head.svg"),
    searchTerms: ["pig head", "animal", "snout", "ears", "tail", "oink"],
    categories: ["Animals"],
  },
  {
    name: "Rabbit",
    path: getIconPath("rabbit.svg"),
    searchTerms: ["rabbit", "animal", "bunny", "ears", "whiskers", "tail"],
    categories: ["Animals"],
  },
  {
    name: "Rat",
    path: getIconPath("rat.svg"),
    searchTerms: ["rat", "animal", "rodent", "whiskers", "tail", "ears"],
    categories: ["Animals"],
  },
  {
    name: "Shark",
    path: getIconPath("shark.svg"),
    searchTerms: ["shark", "animal", "fish", "fins", "gills", "teeth"],
    categories: ["Animals"],
  },
  {
    name: "Snail",
    path: getIconPath("snail.svg"),
    searchTerms: ["snail", "animal", "shell", "slime", "antennae", "eyes"],
    categories: ["Animals"],
  },
  {
    name: "Spider",
    path: getIconPath("spider.svg"),
    searchTerms: ["spider", "animal", "insect", "legs", "eyes", "web"],
    categories: ["Animals"],
  },
  {
    name: "Spider Web",
    path: getIconPath("spider-web.svg"),
    searchTerms: ["spider web", "animal", "insect", "legs", "eyes", "web"],
    categories: ["Animals"],
  },
  {
    name: "Turtle",
    path: getIconPath("turtle.svg"),
    searchTerms: ["turtle", "animal", "reptile", "shell", "slow", "swimming"],
    categories: ["Animals"],
  },
  {
    name: "Unicorn Head",
    path: getIconPath("unicorn-head.svg"),
    searchTerms: [
      "unicorn head",
      "animal",
      "mythical",
      "horn",
      "mane",
      "magic",
    ],
    categories: ["Animals"],
  },
  {
    name: "Waves Shark Fin",
    path: getIconPath("waves-shark-fin.svg"),
    searchTerms: [
      "waves shark fin",
      "shark",
      "animal",
      "fish",
      "fins",
      "gills",
    ],
    categories: ["Animals"],
  },
  {
    name: "Whale",
    path: getIconPath("whale.svg"),
    searchTerms: ["whale", "animal", "ocean", "sea", "water", "swim"],
    categories: ["Animals"],
  },
  {
    name: "Worm",
    path: getIconPath("worm.svg"),
    searchTerms: ["worm", "animal", "invertebrate", "slimy", "crawl", "earth"],
    categories: ["Animals"],
  },
  /* Accounts & Access */
  {
    name: "Activity",
    path: getIconPath("activity.svg"),
    searchTerms: [
      "activity",
      "exercise",
      "workout",
      "heartrate",
      "steps",
      "bpm",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "@ Sign",
    path: getIconPath("at-sign.svg"),
    searchTerms: ["@ sign", "at", "email", "address", "handle", "username"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Award",
    path: getIconPath("award.svg"),
    searchTerms: ["award", "trophy", "prize", "medal", "achievement", "winner"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Ban",
    path: getIconPath("ban.svg"),
    searchTerms: [
      "ban",
      "forbidden",
      "prohibited",
      "stop",
      "block",
      "restrict",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bell",
    path: getIconPath("bell.svg"),
    searchTerms: ["bell", "notification", "alert", "ring", "sound", "alarm"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Book User",
    path: getIconPath("book-user.svg"),
    searchTerms: [
      "book user",
      "reader",
      "student",
      "library",
      "bookworm",
      "read",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bookmark",
    path: getIconPath("bookmark.svg"),
    searchTerms: ["bookmark", "save", "favorite", "read later", "mark", "tag"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bookmark Check",
    path: getIconPath("bookmark-check.svg"),
    searchTerms: [
      "bookmark check",
      "save",
      "favorite",
      "read later",
      "mark",
      "tag",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bookmark Minus",
    path: getIconPath("bookmark-minus.svg"),
    searchTerms: [
      "bookmark minus",
      "save",
      "favorite",
      "read later",
      "mark",
      "tag",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bookmark Plus",
    path: getIconPath("bookmark-plus.svg"),
    searchTerms: [
      "bookmark plus",
      "save",
      "favorite",
      "read later",
      "mark",
      "tag",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Bookmark X",
    path: getIconPath("bookmark-x.svg"),
    searchTerms: [
      "bookmark x",
      "save",
      "favorite",
      "read later",
      "mark",
      "tag",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Building",
    path: getIconPath("building.svg"),
    searchTerms: [
      "building",
      "office",
      "business",
      "work",
      "company",
      "corporate",
    ],
    categories: ["Accounts & Access", "Buildings"],
  },
  {
    name: "Building 2",
    path: getIconPath("building-2.svg"),
    searchTerms: [
      "building 2",
      "office",
      "business",
      "work",
      "company",
      "corporate",
    ],
    categories: ["Accounts & Access", "Buildings"],
  },
  {
    name: "Cake",
    path: getIconPath("cake.svg"),
    searchTerms: ["cake", "birthday", "celebrate", "dessert", "party", "sweet"],
    categories: ["Accounts & Access", "Food & Drink"],
  },
  {
    name: "Circle User",
    path: getIconPath("circle-user.svg"),
    searchTerms: [
      "circle user",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Cog",
    path: getIconPath("cog.svg"),
    searchTerms: [
      "cog",
      "gear",
      "settings",
      "preferences",
      "options",
      "controls",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Contact Round",
    path: getIconPath("contact-round.svg"),
    searchTerms: [
      "contact round",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Cookie",
    path: getIconPath("cookie.svg"),
    searchTerms: [
      "cookie",
      "biscuit",
      "chocolate chip",
      "snack",
      "treat",
      "sweet",
    ],
    categories: ["Accounts & Access", "Food & Drink"],
  },
  {
    name: "Credit Card",
    path: getIconPath("credit-card.svg"),
    searchTerms: [
      "credit card",
      "payment",
      "purchase",
      "buy",
      "money",
      "transaction",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Fingerprint",
    path: getIconPath("fingerprint.svg"),
    searchTerms: [
      "fingerprint",
      "biometric",
      "security",
      "scan",
      "touch",
      "id",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Flag",
    path: getIconPath("flag.svg"),
    searchTerms: [
      "flag",
      "country",
      "nation",
      "banner",
      "patriotism",
      "symbol",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Flag off",
    path: getIconPath("flag-off.svg"),
    searchTerms: [
      "flag off",
      "country",
      "nation",
      "banner",
      "patriotism",
      "symbol",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Frown",
    path: getIconPath("frown.svg"),
    searchTerms: [
      "frown",
      "sad",
      "unhappy",
      "emotion",
      "face",
      "disappointed",
      "emoji",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Gift",
    path: getIconPath("gift.svg"),
    searchTerms: [
      "gift",
      "present",
      "surprise",
      "celebrate",
      "birthday",
      "holiday",
    ],
    categories: ["Accounts & Access", "Holidays"],
  },
  {
    name: "Hand Coins",
    path: getIconPath("hand-coins.svg"),
    searchTerms: ["hand coins", "money", "donate", "give", "charity", "fund"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Handshake",
    path: getIconPath("handshake.svg"),
    searchTerms: ["handshake", "deal", "agreement", "partnership", "greeting"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Id Card",
    path: getIconPath("id-card.svg"),
    searchTerms: [
      "id card",
      "identification",
      "license",
      "passport",
      "credential",
      "badge",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Inbox",
    path: getIconPath("inbox.svg"),
    searchTerms: [
      "inbox",
      "email",
      "messages",
      "mail",
      "letter",
      "communication",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Key",
    path: getIconPath("key.svg"),
    searchTerms: ["key", "lock", "unlock", "password", "access", "secure"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Key Square",
    path: getIconPath("key-square.svg"),
    searchTerms: [
      "key square",
      "lock",
      "unlock",
      "password",
      "access",
      "secure",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Link",
    path: getIconPath("link.svg"),
    searchTerms: ["link", "chain", "connect", "url", "hyperlink", "anchor"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Log In",
    path: getIconPath("log-in.svg"),
    searchTerms: [
      "log in",
      "sign in",
      "enter",
      "login",
      "access",
      "authenticate",
    ],
    categories: ["Accounts & Access", "Arrows"],
  },
  {
    name: "Log Out",
    path: getIconPath("log-out.svg"),
    searchTerms: ["log out", "sign out", "exit", "logout", "leave", "end"],
    categories: ["Accounts & Access", "Arrows"],
  },
  {
    name: "Mail",
    path: getIconPath("mail.svg"),
    searchTerms: ["mail", "email", "letter", "message", "post", "send"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Map",
    path: getIconPath("map.svg"),
    searchTerms: [
      "map",
      "location",
      "gps",
      "navigation",
      "directions",
      "travel",
    ],
    categories: ["Accounts & Access", "Navigation"],
  },
  {
    name: "Map Pinned",
    path: getIconPath("map-pinned.svg"),
    searchTerms: [
      "map pin",
      "location",
      "gps",
      "navigation",
      "directions",
      "travel",
    ],
    categories: ["Accounts & Access", "Navigation"],
  },
  {
    name: "Settings",
    path: getIconPath("settings.svg"),
    searchTerms: [
      "settings",
      "preferences",
      "options",
      "controls",
      "gear",
      "cog",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Settings 2",
    path: getIconPath("settings-2.svg"),
    searchTerms: [
      "settings 2",
      "preferences",
      "options",
      "controls",
      "gear",
      "cog",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Share",
    path: getIconPath("share.svg"),
    searchTerms: ["share", "send", "arrow", "up", "forward", "out"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Share 2",
    path: getIconPath("share-2.svg"),
    searchTerms: ["share 2", "send", "arrow", "up", "forward", "out"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield",
    path: getIconPath("shield.svg"),
    searchTerms: ["shield", "protect", "security", "defend", "safe", "guard"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Alert",
    path: getIconPath("shield-alert.svg"),
    searchTerms: [
      "shield alert",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Ban",
    path: getIconPath("shield-ban.svg"),
    searchTerms: [
      "shield ban",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Check",
    path: getIconPath("shield-check.svg"),
    searchTerms: [
      "shield check",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Off",
    path: getIconPath("shield-off.svg"),
    searchTerms: [
      "shield off",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Plus",
    path: getIconPath("shield-plus.svg"),
    searchTerms: [
      "shield plus",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield Question",
    path: getIconPath("shield-question.svg"),
    searchTerms: [
      "shield question",
      "protect",
      "security",
      "defend",
      "safe",
      "guard",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Shield X",
    path: getIconPath("shield-x.svg"),
    searchTerms: ["shield x", "protect", "security", "defend", "safe", "guard"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Slack",
    path: getIconPath("slack.svg"),
    searchTerms: [
      "slack",
      "logo",
      "brand",
      "communication",
      "chat",
      "messaging",
    ],
    categories: ["Accounts & Access", "Brands"],
  },
  {
    name: "Sliders Horizontal",
    path: getIconPath("sliders-horizontal.svg"),
    searchTerms: [
      "sliders horizontal",
      "settings",
      "preferences",
      "controls",
      "options",
      "gear",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Sliders Vertical",
    path: getIconPath("sliders-vertical.svg"),
    searchTerms: [
      "sliders vertical",
      "settings",
      "preferences",
      "controls",
      "options",
      "gear",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Smile",
    path: getIconPath("smile.svg"),
    searchTerms: ["smile", "happy", "joy", "face", "emotion", "emoji"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Star",
    path: getIconPath("star.svg"),
    searchTerms: ["star", "favorite", "rate", "review", "bookmark", "save"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Tag",
    path: getIconPath("tag.svg"),
    searchTerms: [
      "tag",
      "label",
      "category",
      "metadata",
      "keyword",
      "classify",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Thumbs Down",
    path: getIconPath("thumbs-down.svg"),
    searchTerms: [
      "thumbs down",
      "dislike",
      "disapprove",
      "disagree",
      "no",
      "vote",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Thumbs Up",
    path: getIconPath("thumbs-up.svg"),
    searchTerms: ["thumbs up", "like", "approve", "agree", "yes", "vote"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Trello",
    path: getIconPath("trello.svg"),
    searchTerms: [
      "trello",
      "logo",
      "brand",
      "project management",
      "organization",
      "boards",
    ],
    categories: ["Accounts & Access", "Brands"],
  },
  {
    name: "Twitter",
    path: getIconPath("twitter.svg"),
    searchTerms: ["twitter", "logo", "brand", "social media", "tweet", "bird"],
    categories: ["Accounts & Access", "Brands"],
  },
  {
    name: "User",
    path: getIconPath("user.svg"),
    searchTerms: ["user", "person", "human", "profile", "account", "avatar"],
    categories: ["Accounts & Access"],
  },
  {
    name: "User Check",
    path: getIconPath("user-check.svg"),
    searchTerms: [
      "user check",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "User Minus",
    path: getIconPath("user-minus.svg"),
    searchTerms: [
      "user minus",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "User Pen",
    path: getIconPath("user-pen.svg"),
    searchTerms: [
      "user pen",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "User Plus",
    path: getIconPath("user-plus.svg"),
    searchTerms: [
      "user plus",
      "person",
      "human",
      "profile",
      "account",
      "avatar",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "User X",
    path: getIconPath("user-x.svg"),
    searchTerms: ["user x", "person", "human", "profile", "account", "avatar"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Users",
    path: getIconPath("users.svg"),
    searchTerms: [
      "users",
      "people",
      "humans",
      "profiles",
      "accounts",
      "avatars",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Venetian Mask",
    path: getIconPath("venetian-mask.svg"),
    searchTerms: [
      "venetian mask",
      "mask",
      "carnival",
      "italy",
      "costume",
      "disguise",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Wallet",
    path: getIconPath("wallet.svg"),
    searchTerms: [
      "wallet",
      "money",
      "cash",
      "credit card",
      "payment",
      "purchase",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Wallpaper",
    path: getIconPath("wallpaper.svg"),
    searchTerms: [
      "wallpaper",
      "background",
      "desktop",
      "phone",
      "computer",
      "device",
    ],
    categories: ["Accounts & Access"],
  },
  {
    name: "Waypoints",
    path: getIconPath("waypoints.svg"),
    searchTerms: [
      "waypoints",
      "location",
      "gps",
      "navigation",
      "directions",
      "travel",
    ],
    categories: ["Accounts & Access", "Navigation"],
  },
  {
    name: "Webhook",
    path: getIconPath("webhook.svg"),
    searchTerms: ["webhook", "api", "integration", "web", "hook", "connect"],
    categories: ["Accounts & Access"],
  },
  {
    name: "Wrench",
    path: getIconPath("wrench.svg"),
    searchTerms: ["wrench", "tool", "repair", "fix", "adjust", "settings"],
    categories: ["Accounts & Access"],
  },
  /* Arrows */
  {
    name: "Arrow Big Down",
    path: getIconPath("arrow-big-down.svg"),
    searchTerms: ["arrow big down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Big Left",
    path: getIconPath("arrow-big-left.svg"),
    searchTerms: ["arrow big left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Big Right",
    path: getIconPath("arrow-big-right.svg"),
    searchTerms: ["arrow big right", "arrow", "right", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Big Up",
    path: getIconPath("arrow-big-up.svg"),
    searchTerms: ["arrow big up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Down Left",
    path: getIconPath("arrow-down-left.svg"),
    searchTerms: [
      "arrow down left",
      "arrow",
      "down",
      "left",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Down Right",
    path: getIconPath("arrow-down-right.svg"),
    searchTerms: [
      "arrow down right",
      "arrow",
      "down",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Down Up",
    path: getIconPath("arrow-down-up.svg"),
    searchTerms: ["arrow down up", "arrow", "down", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Down Z-A",
    path: getIconPath("arrow-down-z-a.svg"),
    searchTerms: [
      "arrow down z-a",
      "arrow",
      "down",
      "z-a",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Down",
    path: getIconPath("arrow-down.svg"),
    searchTerms: ["arrow down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Left Right",
    path: getIconPath("arrow-left-right.svg"),
    searchTerms: [
      "arrow left right",
      "arrow",
      "left",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Left",
    path: getIconPath("arrow-left.svg"),
    searchTerms: ["arrow left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Right-Left",
    path: getIconPath("arrow-right-left.svg"),
    searchTerms: [
      "arrow right left",
      "arrow",
      "right",
      "left",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Right",
    path: getIconPath("arrow-right.svg"),
    searchTerms: ["arrow right", "arrow", "right", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Up A-Z",
    path: getIconPath("arrow-up-a-z.svg"),
    searchTerms: ["arrow up a-z", "arrow", "up", "a-z", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Up Down",
    path: getIconPath("arrow-up-down.svg"),
    searchTerms: ["arrow up down", "arrow", "up", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Up Left",
    path: getIconPath("arrow-up-left.svg"),
    searchTerms: ["arrow up left", "arrow", "up", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Up Right",
    path: getIconPath("arrow-up-right.svg"),
    searchTerms: [
      "arrow up right",
      "arrow",
      "up",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Arrow Up",
    path: getIconPath("arrow-up.svg"),
    searchTerms: ["arrow up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Calendar Sync",
    path: getIconPath("calendar-sync.svg"),
    searchTerms: [
      "calendar sync",
      "arrow",
      "sync",
      "refresh",
      "update",
      "repeat",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Chevron Down",
    path: getIconPath("chevron-down.svg"),
    searchTerms: ["chevron down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevron Left",
    path: getIconPath("chevron-left.svg"),
    searchTerms: ["chevron left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevron Right",
    path: getIconPath("chevron-right.svg"),
    searchTerms: ["chevron right", "arrow", "right", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevron Up",
    path: getIconPath("chevron-up.svg"),
    searchTerms: ["chevron up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Down-Up",
    path: getIconPath("chevrons-down-up.svg"),
    searchTerms: [
      "chevrons down-up",
      "arrow",
      "down",
      "up",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Down",
    path: getIconPath("chevrons-down.svg"),
    searchTerms: ["chevrons down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Left-Right",
    path: getIconPath("chevrons-left-right.svg"),
    searchTerms: [
      "chevrons left-right",
      "arrow",
      "left",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Left",
    path: getIconPath("chevrons-left.svg"),
    searchTerms: ["chevrons left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Right-Left",
    path: getIconPath("chevrons-right-left.svg"),
    searchTerms: [
      "chevrons right-left",
      "arrow",
      "right",
      "left",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Right",
    path: getIconPath("chevrons-right.svg"),
    searchTerms: ["chevrons right", "arrow", "right", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Up-Down",
    path: getIconPath("chevrons-up-down.svg"),
    searchTerms: [
      "chevrons up-down",
      "arrow",
      "up",
      "down",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Chevrons Up",
    path: getIconPath("chevrons-up.svg"),
    searchTerms: ["chevrons up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Down",
    path: getIconPath("circle-arrow-down.svg"),
    searchTerms: ["circle arrow down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Left",
    path: getIconPath("circle-arrow-left.svg"),
    searchTerms: ["circle arrow left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Out Down Left",
    path: getIconPath("circle-arrow-out-down-left.svg"),
    searchTerms: [
      "circle arrow out down left",
      "arrow",
      "down",
      "left",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Out Down Right",
    path: getIconPath("circle-arrow-out-down-right.svg"),
    searchTerms: [
      "circle arrow out down right",
      "arrow",
      "down",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Out Up Left",
    path: getIconPath("circle-arrow-out-up-left.svg"),
    searchTerms: [
      "circle arrow out up left",
      "arrow",
      "up",
      "left",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Out Up Right",
    path: getIconPath("circle-arrow-out-up-right.svg"),
    searchTerms: [
      "circle arrow out up right",
      "arrow",
      "up",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Right",
    path: getIconPath("circle-arrow-right.svg"),
    searchTerms: ["circle arrow right", "arrow", "right", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Arrow Up",
    path: getIconPath("circle-arrow-up.svg"),
    searchTerms: ["circle arrow up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Chevron Down",
    path: getIconPath("circle-chevron-down.svg"),
    searchTerms: ["circle chevron down", "arrow", "down", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Chevron Left",
    path: getIconPath("circle-chevron-left.svg"),
    searchTerms: ["circle chevron left", "arrow", "left", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Circle Chevron Right",
    path: getIconPath("circle-chevron-right.svg"),
    searchTerms: [
      "circle chevron right",
      "arrow",
      "right",
      "direction",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Circle Chevron Up",
    path: getIconPath("circle-chevron-up.svg"),
    searchTerms: ["circle chevron up", "arrow", "up", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Clipboard Copy",
    path: getIconPath("clipboard-copy.svg"),
    searchTerms: [
      "clipboard copy",
      "arrow",
      "copy",
      "duplicate",
      "paste",
      "clone",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Clipboard Paste",
    path: getIconPath("clipboard-paste.svg"),
    searchTerms: [
      "clipboard paste",
      "arrow",
      "paste",
      "copy",
      "duplicate",
      "clone",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Cloud Download",
    path: getIconPath("cloud-download.svg"),
    searchTerms: [
      "cloud download",
      "arrow",
      "download",
      "save",
      "export",
      "backup",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Cloud Upload",
    path: getIconPath("cloud-upload.svg"),
    searchTerms: [
      "cloud upload",
      "arrow",
      "upload",
      "save",
      "import",
      "restore",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Database Backup",
    path: getIconPath("database-backup.svg"),
    searchTerms: [
      "database backup",
      "arrow",
      "backup",
      "save",
      "export",
      "restore",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Delete",
    path: getIconPath("delete.svg"),
    searchTerms: ["delete", "remove", "trash", "bin", "erase", "clear"],
    categories: ["Arrows"],
  },
  {
    name: "Download",
    path: getIconPath("download.svg"),
    searchTerms: ["download", "save", "export", "backup", "get", "fetch"],
    categories: ["Arrows"],
  },
  {
    name: "External Link",
    path: getIconPath("external-link.svg"),
    searchTerms: ["external link", "link", "arrow", "out", "new tab", "open"],
    categories: ["Arrows"],
  },
  {
    name: "Fast Forward",
    path: getIconPath("fast-forward.svg"),
    searchTerms: ["fast forward", "arrow", "skip", "next", "forward", "right"],
    categories: ["Arrows"],
  },
  {
    name: "File Down",
    path: getIconPath("file-down.svg"),
    searchTerms: ["file down", "arrow", "download", "save", "export", "get"],
    categories: ["Arrows"],
  },
  {
    name: "File Input",
    path: getIconPath("file-input.svg"),
    searchTerms: ["file input", "arrow", "upload", "import", "get", "fetch"],
    categories: ["Arrows"],
  },
  {
    name: "File Output",
    path: getIconPath("file-output.svg"),
    searchTerms: ["file output", "arrow", "download", "save", "export", "get"],
    categories: ["Arrows"],
  },
  {
    name: "File Up",
    path: getIconPath("file-up.svg"),
    searchTerms: ["file up", "arrow", "upload", "import", "get", "fetch"],
    categories: ["Arrows"],
  },
  {
    name: "Fold Horizontal",
    path: getIconPath("fold-horizontal.svg"),
    searchTerms: ["fold horizontal", "arrow", "fold", "collapse", "hide", "up"],
    categories: ["Arrows"],
  },
  {
    name: "Fold Vertical",
    path: getIconPath("fold-vertical.svg"),
    searchTerms: ["fold vertical", "arrow", "fold", "collapse", "hide", "up"],
    categories: ["Arrows"],
  },
  {
    name: "Folder Down",
    path: getIconPath("folder-down.svg"),
    searchTerms: ["folder down", "arrow", "download", "save", "export", "get"],
    categories: ["Arrows"],
  },
  {
    name: "Folder Input",
    path: getIconPath("folder-input.svg"),
    searchTerms: ["folder input", "arrow", "upload", "import", "get", "fetch"],
    categories: ["Arrows"],
  },
  {
    name: "Folder Output",
    path: getIconPath("folder-output.svg"),
    searchTerms: [
      "folder output",
      "arrow",
      "download",
      "save",
      "export",
      "get",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Folder Sync",
    path: getIconPath("folder-sync.svg"),
    searchTerms: [
      "folder sync",
      "arrow",
      "sync",
      "refresh",
      "update",
      "repeat",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Folder Up",
    path: getIconPath("folder-up.svg"),
    searchTerms: ["folder up", "arrow", "upload", "import", "get", "fetch"],
    categories: ["Arrows"],
  },
  {
    name: "Git Compare Arrows",
    path: getIconPath("git-compare-arrows.svg"),
    searchTerms: [
      "git compare arrows",
      "arrow",
      "compare",
      "diff",
      "change",
      "update",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Git Pull Request Arrow",
    path: getIconPath("git-pull-request-arrow.svg"),
    searchTerms: [
      "git pull request arrows",
      "arrow",
      "pull request",
      "merge",
      "code",
      "update",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Git Pull Request Create Arrow",
    path: getIconPath("git-pull-request-create-arrow.svg"),
    searchTerms: [
      "git pull request create arrow",
      "arrow",
      "pull request",
      "merge",
      "code",
      "update",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Hard Drive Download",
    path: getIconPath("hard-drive-download.svg"),
    searchTerms: [
      "hard drive download",
      "arrow",
      "download",
      "save",
      "export",
      "backup",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Hard Drive Upload",
    path: getIconPath("hard-drive-upload.svg"),
    searchTerms: [
      "hard drive upload",
      "arrow",
      "upload",
      "save",
      "import",
      "restore",
    ],
    categories: ["Arrows"],
  },
  {
    name: "History",
    path: getIconPath("history.svg"),
    searchTerms: ["history", "arrow", "back", "forward", "time", "record"],
    categories: ["Arrows"],
  },
  {
    name: "Import",
    path: getIconPath("import.svg"),
    searchTerms: ["import", "arrow", "upload", "get", "fetch", "receive"],
    categories: ["Arrows"],
  },
  {
    name: "Iteration CCW",
    path: getIconPath("iteration-ccw.svg"),
    searchTerms: [
      "iteration ccw",
      "arrow",
      "repeat",
      "refresh",
      "update",
      "reload",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Iteration CW",
    path: getIconPath("iteration-cw.svg"),
    searchTerms: [
      "iteration cw",
      "arrow",
      "repeat",
      "refresh",
      "update",
      "reload",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Merge",
    path: getIconPath("merge.svg"),
    searchTerms: ["merge", "arrow", "combine", "join", "unite", "connect"],
    categories: ["Arrows"],
  },
  {
    name: "Milestone",
    path: getIconPath("milestone.svg"),
    searchTerms: [
      "milestone",
      "arrow",
      "goal",
      "achievement",
      "target",
      "flag",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Mouse Pointer",
    path: getIconPath("mouse-pointer.svg"),
    searchTerms: [
      "mouse pointer",
      "arrow",
      "cursor",
      "click",
      "select",
      "point",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Move Down",
    path: getIconPath("move-down.svg"),
    searchTerms: ["move down", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move Horizontal",
    path: getIconPath("move-horizontal.svg"),
    searchTerms: ["move horizontal", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move Left",
    path: getIconPath("move-left.svg"),
    searchTerms: ["move left", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move Right",
    path: getIconPath("move-right.svg"),
    searchTerms: ["move right", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move Up",
    path: getIconPath("move-up.svg"),
    searchTerms: ["move up", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move Vertical",
    path: getIconPath("move-vertical.svg"),
    searchTerms: ["move vertical", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Move",
    path: getIconPath("move.svg"),
    searchTerms: ["move", "arrow", "move", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Panel Bottom Open",
    path: getIconPath("panel-bottom-open.svg"),
    searchTerms: [
      "panel bottom open",
      "arrow",
      "open",
      "expand",
      "down",
      "show",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Panel Left Open",
    path: getIconPath("panel-left-open.svg"),
    searchTerms: ["panel left open", "arrow", "open", "expand", "left", "show"],
    categories: ["Arrows"],
  },
  {
    name: "Panel Right Open",
    path: getIconPath("panel-right-open.svg"),
    searchTerms: [
      "panel right open",
      "arrow",
      "open",
      "expand",
      "right",
      "show",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Panel Top Open",
    path: getIconPath("panel-top-open.svg"),
    searchTerms: ["panel top open", "arrow", "open", "expand", "up", "show"],
    categories: ["Arrows"],
  },
  {
    name: "Phone Forwarded",
    path: getIconPath("phone-forwarded.svg"),
    searchTerms: [
      "phone forwarded",
      "arrow",
      "forward",
      "call",
      "phone",
      "transfer",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Phone Incoming",
    path: getIconPath("phone-incoming.svg"),
    searchTerms: [
      "phone incoming",
      "arrow",
      "incoming",
      "call",
      "phone",
      "receive",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Phone Outgoing",
    path: getIconPath("phone-outgoing.svg"),
    searchTerms: [
      "phone outgoing",
      "arrow",
      "outgoing",
      "call",
      "phone",
      "send",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Play",
    path: getIconPath("play.svg"),
    searchTerms: ["play", "arrow", "start", "begin", "go", "forward"],
    categories: ["Arrows"],
  },
  {
    name: "Refresh CCW",
    path: getIconPath("refresh-ccw.svg"),
    searchTerms: ["refresh ccw", "arrow", "repeat", "update", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Refresh CW",
    path: getIconPath("refresh-cw.svg"),
    searchTerms: ["refresh cw", "arrow", "repeat", "update", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Repeat",
    path: getIconPath("repeat.svg"),
    searchTerms: ["repeat", "arrow", "loop", "cycle", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Repeat 2",
    path: getIconPath("repeat-2.svg"),
    searchTerms: ["repeat 2", "arrow", "loop", "cycle", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Rewind",
    path: getIconPath("rewind.svg"),
    searchTerms: ["rewind", "arrow", "skip", "back", "previous", "left"],
    categories: ["Arrows"],
  },
  {
    name: "Rotate CCW",
    path: getIconPath("rotate-ccw.svg"),
    searchTerms: ["rotate ccw", "arrow", "repeat", "update", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Rotate CW",
    path: getIconPath("rotate-cw.svg"),
    searchTerms: ["rotate cw", "arrow", "repeat", "update", "reload", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Shuffle",
    path: getIconPath("shuffle.svg"),
    searchTerms: ["shuffle", "arrow", "random", "mix", "order", "sync"],
    categories: ["Arrows"],
  },
  {
    name: "Signpost",
    path: getIconPath("signpost.svg"),
    searchTerms: ["signpost", "arrow", "direction", "point", "guide", "post"],
    categories: ["Arrows"],
  },
  {
    name: "Signpost Big",
    path: getIconPath("signpost-big.svg"),
    searchTerms: ["signpost big", "arrow", "big", "direction", "point"],
    categories: ["Arrows"],
  },
  {
    name: "Sunrise",
    path: getIconPath("sunrise.svg"),
    searchTerms: ["sunrise", "arrow", "morning", "day", "sun", "rise"],
    categories: ["Arrows"],
  },
  {
    name: "Sunset",
    path: getIconPath("sunset.svg"),
    searchTerms: ["sunset", "arrow", "evening", "night", "sun", "set"],
    categories: ["Arrows"],
  },
  {
    name: "Trending Down",
    path: getIconPath("trending-down.svg"),
    searchTerms: [
      "trending down",
      "arrow",
      "down",
      "trend",
      "decrease",
      "fall",
    ],
    categories: ["Arrows"],
  },
  {
    name: "Trending Up",
    path: getIconPath("trending-up.svg"),
    searchTerms: ["trending up", "arrow", "up", "trend", "increase", "rise"],
    categories: ["Arrows"],
  },
  {
    name: "Upload",
    path: getIconPath("upload.svg"),
    searchTerms: ["upload", "arrow", "save", "import", "restore", "send"],
    categories: ["Arrows"],
  },
  /* Brands */
  {
    name: "Chrome",
    path: getIconPath("chrome.svg"),
    searchTerms: ["chrome", "logo", "brand", "browser", "internet", "google"],
    categories: ["Brands"],
  },
  {
    name: "Facebook",
    path: getIconPath("facebook.svg"),
    searchTerms: [
      "facebook",
      "logo",
      "brand",
      "social media",
      "connect",
      "share",
    ],
    categories: ["Brands"],
  },
  {
    name: "Figma",
    path: getIconPath("figma.svg"),
    searchTerms: ["figma", "logo", "brand", "design", "ui", "ux"],
    categories: ["Brands"],
  },
  {
    name: "Github",
    path: getIconPath("github.svg"),
    searchTerms: ["github", "logo", "brand", "code", "repository", "git"],
    categories: ["Brands"],
  },
  {
    name: "Gitlab",
    path: getIconPath("gitlab.svg"),
    searchTerms: ["gitlab", "logo", "brand", "code", "repository", "git"],
    categories: ["Brands"],
  },
  {
    name: "Instagram",
    path: getIconPath("instagram.svg"),
    searchTerms: [
      "instagram",
      "logo",
      "brand",
      "social media",
      "photo",
      "camera",
    ],
    categories: ["Brands"],
  },
  {
    name: "Linkedin",
    path: getIconPath("linkedin.svg"),
    searchTerms: [
      "linkedin",
      "logo",
      "brand",
      "social media",
      "connect",
      "job",
    ],
    categories: ["Brands"],
  },
  {
    name: "Twitch",
    path: getIconPath("twitch.svg"),
    searchTerms: ["twitch", "logo", "brand", "stream", "gaming", "live"],
    categories: ["Brands"],
  },
  /* Buildings */
  {
    name: "Anvil",
    path: getIconPath("anvil.svg"),
    searchTerms: ["anvil", "blacksmith", "forge", "metal", "craft", "hammer"],
    categories: ["Buildings"],
  },
  {
    name: "Brick Wall",
    path: getIconPath("brick-wall.svg"),
    searchTerms: ["brick wall", "wall", "brick", "building", "construction"],
    categories: ["Buildings"],
  },
  {
    name: "Castle",
    path: getIconPath("castle.svg"),
    searchTerms: [
      "castle",
      "fortress",
      "kingdom",
      "royal",
      "medieval",
      "stone",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Chrome",
    path: getIconPath("chrome.svg"),
    searchTerms: ["chrome", "logo", "brand", "browser", "internet", "google"],
    categories: ["Buildings"],
  },
  {
    name: "Church",
    path: getIconPath("church.svg"),
    searchTerms: ["church", "religion", "faith", "god", "pray", "worship"],
    categories: ["Buildings"],
  },
  {
    name: "Cuboid",
    path: getIconPath("cuboid.svg"),
    searchTerms: ["cuboid", "cube", "box", "3d", "dimension", "shape"],
    categories: ["Buildings"],
  },
  {
    name: "Dam",
    path: getIconPath("dam.svg"),
    searchTerms: ["dam", "water", "river", "lake", "reservoir", "flood"],
    categories: ["Buildings"],
  },
  {
    name: "Facebook",
    path: getIconPath("facebook.svg"),
    searchTerms: [
      "facebook",
      "logo",
      "brand",
      "social media",
      "connect",
      "share",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Factory",
    path: getIconPath("factory.svg"),
    searchTerms: ["factory", "industry", "manufacture", "production", "work"],
    categories: ["Buildings"],
  },
  {
    name: "Fence",
    path: getIconPath("fence.svg"),
    searchTerms: ["fence", "wall", "barrier", "border", "property", "garden"],
    categories: ["Buildings"],
  },
  {
    name: "Graduation Cap",
    path: getIconPath("graduation-cap.svg"),
    searchTerms: [
      "graduation cap",
      "cap",
      "hat",
      "degree",
      "education",
      "learn",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Hospital",
    path: getIconPath("hospital.svg"),
    searchTerms: ["hospital", "clinic", "health", "care", "medical", "nurse"],
    categories: ["Buildings"],
  },
  {
    name: "House",
    path: getIconPath("house.svg"),
    searchTerms: ["house", "home", "building", "family", "property", "live"],
    categories: ["Buildings"],
  },
  {
    name: "Igloo",
    path: getIconPath("igloo.svg"),
    searchTerms: ["igloo", "ice", "snow", "cold", "winter", "eskimo"],
    categories: ["Buildings"],
  },
  {
    name: "Landmark",
    path: getIconPath("landmark.svg"),
    searchTerms: [
      "landmark",
      "monument",
      "tourism",
      "historic",
      "site",
      "place",
    ],
    categories: ["Buildings"],
  },
  {
    name: "School",
    path: getIconPath("school.svg"),
    searchTerms: [
      "school",
      "education",
      "learn",
      "student",
      "teacher",
      "study",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Store",
    path: getIconPath("store.svg"),
    searchTerms: ["store", "shop", "retail", "buy", "sell", "purchase"],
    categories: ["Buildings"],
  },
  {
    name: "University",
    path: getIconPath("university.svg"),
    searchTerms: [
      "university",
      "school",
      "college",
      "learn",
      "student",
      "study",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Utility Pole",
    path: getIconPath("utility-pole.svg"),
    searchTerms: [
      "utility pole",
      "pole",
      "electricity",
      "power",
      "cable",
      "wire",
    ],
    categories: ["Buildings"],
  },
  {
    name: "Warehouse",
    path: getIconPath("warehouse.svg"),
    searchTerms: [
      "warehouse",
      "store",
      "storage",
      "stock",
      "inventory",
      "supply",
    ],
    categories: ["Buildings"],
  },
  /* Charts */
  {
    name: "Area Chart",
    path: getIconPath("chart-area.svg"),
    searchTerms: ["area chart", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "Bar Chart Big",
    path: getIconPath("chart-bar-big.svg"),
    searchTerms: ["bar chart big", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "Bar Chart Decreasing",
    path: getIconPath("chart-bar-decreasing.svg"),
    searchTerms: [
      "bar chart decreasing",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Bar Chart Increasing",
    path: getIconPath("chart-bar-increasing.svg"),
    searchTerms: [
      "bar chart increasing",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Bar Chart Stacked",
    path: getIconPath("chart-bar-stacked.svg"),
    searchTerms: [
      "bar chart stacked",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Candlestick Chart",
    path: getIconPath("chart-candlestick.svg"),
    searchTerms: [
      "candlestick chart",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Column Chart Big",
    path: getIconPath("chart-column-big.svg"),
    searchTerms: ["chart column big", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "Column Chart Decreasing",
    path: getIconPath("chart-column-decreasing.svg"),
    searchTerms: [
      "chart column decreasing",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Column Chart Increasing",
    path: getIconPath("chart-column-increasing.svg"),
    searchTerms: [
      "chart column increasing",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Column Chart Stacked",
    path: getIconPath("chart-column-stacked.svg"),
    searchTerms: [
      "chart column stacked",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Line Chart",
    path: getIconPath("chart-line.svg"),
    searchTerms: ["line chart", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "Network Chart",
    path: getIconPath("chart-network.svg"),
    searchTerms: ["network chart", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "No Axes Combined Chart",
    path: getIconPath("chart-no-axes-combined.svg"),
    searchTerms: [
      "no axes combined chart",
      "chart",
      "graph",
      "data",
      "line",
      "plot",
    ],
    categories: ["Charts"],
  },
  {
    name: "Pie Chart",
    path: getIconPath("chart-pie.svg"),
    searchTerms: ["pie chart", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  {
    name: "Venn Diagram",
    path: getIconPath("venn.svg"),
    searchTerms: ["venn diagram", "chart", "graph", "data", "line", "plot"],
    categories: ["Charts"],
  },
  /* Communication */
  {
    name: "Antenna",
    path: getIconPath("antenna.svg"),
    searchTerms: ["antenna", "signal", "radio", "broadcast", "transmit", "wave"],
    categories: ["Communication"],
  },
  {
    name: "Audio Lines",
    path: getIconPath("audio-lines.svg"),
    searchTerms: ["audio lines", "sound", "music", "wave", "volume", "listen"],
    categories: ["Communication"],
  },
  {
    name: "Audio Waveform",
    path: getIconPath("audio-waveform.svg"),
    searchTerms: ["audio waveform", "sound", "music", "wave", "volume", "listen"],
    categories: ["Communication"],
  },
  {
    name: "Camera",
    path: getIconPath("camera.svg"),
    searchTerms: ["camera", "photo", "picture", "capture", "record", "shoot"],
    categories: ["Communication"],
  },
  {
    name: "Cassette Tape",
    path: getIconPath("cassette-tape.svg"),
    searchTerms: ["cassette tape", "audio", "music", "record", "play", "listen"],
    categories: ["Communication"],
  },
  {
    name: "CCTV",
    path: getIconPath("cctv.svg"),
    searchTerms: ["cctv", "camera", "security", "surveillance", "monitor", "watch"],
    categories: ["Communication"],
  },
  {
    name: "Ethernet Port",
    path: getIconPath("ethernet-port.svg"),
    searchTerms: ["ethernet port", "network", "internet", "connection", "plug", "socket"],
    categories: ["Communication"],
  },
  {
    name: "Microphone",
    path: getIconPath("microphone.svg"),
    searchTerms: ["microphone", "audio", "sound", "record", "speak", "talk"],
    categories: ["Communication"],
  },
  {
    name: "Newspaper",
    path: getIconPath("newspaper.svg"),
    searchTerms: ["newspaper", "news", "media", "press", "article", "headline"],
    categories: ["Communication"],
  },
  {
    name: "NFC",
    path: getIconPath("nfc.svg"),
    searchTerms: ["nfc", "near field communication", "wireless", "contactless", "tag", "smart"],
    categories: ["Communication"],
  },
  {
    name: "Presentation",
    path: getIconPath("presentation.svg"),
    searchTerms: ["presentation", "slide", "talk", "show", "lecture", "speak"],
    categories: ["Communication"],
  },
  {
    name: "Projector",
    path: getIconPath("projector.svg"),
    searchTerms: ["projector", "screen", "display", "show", "presentation", "movie"],
    categories: ["Communication"],
  },
  {
    name: "Radar",
    path: getIconPath("radar.svg"),
    searchTerms: ["radar", "signal", "wave", "detect", "scan", "monitor"],
    categories: ["Communication"],
  },
  {
    name: "Send Horizontal",
    path: getIconPath("send-horizontal.svg"),
    searchTerms: ["send horizontal", "send", "arrow", "direction", "point", "transfer"],
    categories: ["Communication"],
  },
  {
    name: "Send",
    path: getIconPath("send.svg"),
    searchTerms: ["send", "arrow", "direction", "point", "transfer"],
    categories: ["Communication"],
  },
  {
    name: "TV",
    path: getIconPath("tv.svg"),
    searchTerms: ["tv", "television", "screen", "watch", "show", "movie"],
    categories: ["Communication"],
  },
  {
    name: "Video",
    path: getIconPath("video.svg"),
    searchTerms: ["video", "camera", "record", "movie", "film", "watch"],
    categories: ["Communication"],
  },
  {
    name: "Video Tape",
    path: getIconPath("videotape.svg"),
    searchTerms: ["video tape", "audio", "music", "record", "play", "listen"],
    categories: ["Communication"],
  },
  {
    name: "Volume 1",
    path: getIconPath("volume-1.svg"),
    searchTerms: ["volume 1", "sound", "music", "audio", "listen", "hear"],
    categories: ["Communication"],
  },
  {
    name: "Volume 2",
    path: getIconPath("volume-2.svg"),
    searchTerms: ["volume 2", "sound", "music", "audio", "listen", "hear"],
    categories: ["Communication"],
  },
  {
    name: "Webcam",
    path: getIconPath("webcam.svg"),
    searchTerms: ["webcam", "camera", "video", "record", "stream", "live"],
    categories: ["Communication"],
  }
];
